---
apiVersion: v1
kind: Service
metadata:
  name: flask-echo
  labels:
    app: flask-echo
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: flask-echo
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: flask-echo
spec:
  serviceName: "flask-echo"
  replicas: 2
  selector:
    matchLabels:
      app: flask-echo
  template:
    metadata:
      labels:
        app: flask-echo
    spec:
      containers:
      - name: flask-echo
        imagePullPolicy: IfNotPresent
        # if already distributed to Docker engines image cache, on
        # Kubernetes Nodes, else use fully-qualified name pointing to
        # Docker registry being in use.
        image: flask-echo:latest
        command: ['/usr/bin/python3']
        args: ['/var/www/app/app.py']
        ports:
        - containerPort: 8080
          name: web
